import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from"@/components/Footer/Footer";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <nav>
          <ul>
            <li>
              <Link href="/products">Produtos</Link>
            </li>
            <li>
              <Link href="/tecnologias">Tecnologias</Link>
            </li>
            <li>
              <Link href="/municipalities">Municipalities</Link>
            </li>
          </ul>
        </nav>
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
